on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name to be deployed'     
        required: true
jobs:
  printResult:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Service: ${{ github.event.inputs.service }}"
