on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name to be deployed'     
        required: true
        type: string
  workflow_call:
    inputs:
      service:
        description: 'Service name to be deployed'     
        required: true
        type: string
jobs:
  printResult:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Service name: ${{ inputs.service }}"
  printResult2:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Service name: ${{ inputs.service }}"
    container:
      image: proget.repo.symbotic.corp/dev_images/library/symverse-deploy:v2.1.2
