on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name to be deployed'     
        required: true
        type: string
  workflow_call:
    inputs:
      service:
        description: 'Service name to be deployed'     
        required: true
        type: string
jobs:
  printResult:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Service from dispatch: ${{ github.event.inputs.service }}. Service from call ${{ inputs.service }}"
